#!/usr/bin/env ansible-playbook
---

# Setup SSH authorized keys on Vyatta/Vyos and Unifi/EdgeRouter Devices

- name: check for existance of /config/local
  stat:
    path: /config/local
  register: config_local
  
- name: "Notice if /config/local already exists"
  debug:
    msg: "NOTICE: /config/local already exists"
  when: config_local.exists == true

- name: Create persistent local config directory
  file:
    path: /config/local
    state: directory
  when: config_local.exists == false

- name: check for existance of /config/local/authorized-ssh-key
  stat:
    path: /config/local/authorized-ssh-key
  register: authorized_ssh_key

- name: "Notice if /config/local/authorized-ssh-key already exists"
  debug:
    msg: "NOTICE: /config/local/authorized-ssh-key already exists"
  when: authorized_ssh_key.exists == true

- name: Copy SSH public key to router
  copy:
    src: "{{ netapl_ssh_authorized_key }}"
    dest: /config/local/authorized-ssh-key
  when: 
    - config_local.exists == true
    - authorized_ssh_key.exists == false

- name: check for existance of /config/local/load-authorized-key.sh
  stat:
    path: /config/local/load-authorized-key.sh
  register: load_authorized_key_sh

- name: "Notice if /config/local/load-authorized-key.sh already exists"
  debug:
    msg: "NOTICE: /config/local/load-authorized-key.sh already exists"
  when: authorized_ssh_key.exists == true

- name: Copy script to load public key into config
  template:
    src: load-authorized-key.sh.j2
    dest: /config/local/load-authorized-key.sh
    mode: 0755
  when: 
    - config_local.exists == true
    - load_authorized_key_sh.exists == false

- name: Load SSH public key into config
  command: /config/local/load-authorized-key.sh
  when:
    - config_local.exists == true
    - authorized_ssh_key.exists == true
    - load_authorized_key_sh.exists == true
